/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: voice_inside (https://sketchfab.com/voice_inside)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/atom-b505bc59e6fb48569e4f032a0734f743
title: Atom
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Atom(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/atom.gltf')
  // eslint-disable-next-line no-unused-vars
  const { actions } = useAnimations(animations, group)
  return (
    // eslint-disable-next-line react/jsx-props-no-spreading
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[0, 0.08, 0.01]}>
          <group
            name="electron_2"
            position={[0.14, -0.01, -0.08]}
            rotation={[0.85, 0.75, 3.05]}
          >
            <mesh
              geometry={nodes.electron_2_0.geometry}
              material={nodes.electron_2_0.material}
            />
          </group>
          <group position={[0.13, -0.01, -0.1]} rotation={[3.07, -0.1, -0.08]}>
            <mesh
              geometry={nodes.electron__3_0.geometry}
              material={nodes.electron__3_0.material}
            />
          </group>
          <group
            position={[0.13, -0.01, -0.08]}
            rotation={[-1.01, -0.32, 0.47]}
          >
            <mesh
              geometry={nodes.electron_1_0.geometry}
              material={nodes.electron_1_0.material}
            />
          </group>
          <group
            position={[0, 0, 0]}
            rotation={[1.01, -0.03, -0.06]}
            scale={[0.5, 0.5, 0.5]}
          >
            <mesh geometry={nodes.core_0.geometry} material={materials.core} />
          </group>
          <group rotation={[0.82, 0.75, 3.09]} scale={[1, 1, 1]}>
            <mesh
              geometry={nodes.electron_shell_0.geometry}
              material={nodes.electron_shell_0.material}
            />
          </group>
          <group rotation={[-0.99, -0.33, 0.45]} scale={[1, 1, 1]}>
            <mesh
              geometry={nodes.electron_shell2_0.geometry}
              material={nodes.electron_shell2_0.material}
            />
          </group>
          <group rotation={[3.08, -0.1, -0.05]} scale={[1, 1, 1]}>
            <mesh
              geometry={nodes.electron_shell3_0.geometry}
              material={nodes.electron_shell3_0.material}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/atom.gltf')
