/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: rivaiamin (https://sketchfab.com/rivaiamin)
license: CC-BY-ND-4.0 (http://creativecommons.org/licenses/by-nd/4.0/)
source: https://sketchfab.com/3d-models/lost-programmer-43d32e4f459f4857a054579da61bb3d6
title: Lost Programmer
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Programmer(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/programmer.gltf')
  return (
    // eslint-disable-next-line react/jsx-props-no-spreading
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[0.2, 0.13, -0.22]}>
          <group
            position={[-0.03, -0.44, -0.47]}
            rotation={[2.38, 0, 0]}
            scale={[0.15, 0.15, 0.15]}
          >
            <mesh
              geometry={nodes.Cube005_0.geometry}
              material={materials.laptop_tex}
            />
          </group>
          <group
            position={[0, 0.75, -0.09]}
            rotation={[1.26, 0, 0]}
            scale={[1, 1, 1]}
          >
            <primitive object={nodes.my_rig_rootJoint} />
            <group position={[0, -0.07, 0]} scale={0.36}>
              <mesh
                geometry={nodes.hair_0.geometry}
                material={materials.cloth}
              />
              <mesh
                geometry={nodes.hair_1.geometry}
                material={materials.solidify}
              />
            </group>
            <group position={[0, -0.07, 0]} scale={0.36}>
              <mesh geometry={nodes.me_0.geometry} material={materials.body} />
              <mesh
                geometry={nodes.me_1.geometry}
                material={materials.solidify_0}
              />
            </group>
            <group position={[0, -0.07, 0]} scale={0.36}>
              <mesh
                geometry={nodes.me002_0.geometry}
                material={materials.cloth_0}
              />
              <mesh
                geometry={nodes.me002_1.geometry}
                material={materials.solidify_1}
              />
            </group>
            <group position={[0, -0.07, 0]} scale={0.36}>
              <mesh
                geometry={nodes.kemeja_0.geometry}
                material={materials.cloth_1}
              />
              <mesh
                geometry={nodes.kemeja_1.geometry}
                material={materials.solidify_2}
              />
            </group>
          </group>
          <group
            position={[2.4, 0.75, -0.43]}
            rotation={[-0.46, 0.3, -0.93]}
            scale={[0.11, 0.11, 0.11]}
          >
            <mesh
              geometry={nodes.bool1185_0.geometry}
              material={materials.Material}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/programmer.gltf')
